### ISSUE TITLE
Push to filetree WebDAV remote fails

### ISSUE THREAD

**Issue by mslw** [datalad/datalad-next#61]
Using Python API on Juseless, with `xxx` being a filetree mode WebDAV remote...

```
>>> from datalad import api as dl
>>> dl.push(dataset='.', to='xxx')
Push to 'xxx':  25%|████████████████████▌                                                             | 1.00/4.00 [00:00<00:00, 3.29k Steps/sTraceback (most recent call last):50%|████████████████████████████████▌                                | 2.00/4.00 [00:00<00:00, 3.66k Steps/s]
  File "<stdin>", line 1, in <module>                                                                                                         
  File "/data/group/psyinf/sfb1451/motor-assessment/venv/lib/python3.7/site-packages/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "/data/group/psyinf/sfb1451/motor-assessment/venv/lib/python3.7/site-packages/datalad/interface/utils.py", line 439, in return_func
    results = list(results)
  File "/data/group/psyinf/sfb1451/motor-assessment/venv/lib/python3.7/site-packages/datalad/interface/utils.py", line 369, in generator_func
    allkwargs):
  File "/data/group/psyinf/sfb1451/motor-assessment/venv/lib/python3.7/site-packages/datalad/interface/utils.py", line 544, in _process_results
    for res in results:
  File "/data/group/psyinf/sfb1451/motor-assessment/venv/lib/python3.7/site-packages/datalad/core/distributed/push.py", line 263, in __call__
    got_path_arg=True if path else False)
  File "/data/group/psyinf/sfb1451/motor-assessment/venv/lib/python3.7/site-packages/datalad/core/distributed/push.py", line 598, in _push
    got_path_arg=got_path_arg,
  File "/data/group/psyinf/sfb1451/motor-assessment/venv/lib/python3.7/site-packages/datalad/core/distributed/push.py", line 621, in _push
    got_path_arg=got_path_arg,
  File "/data/group/psyinf/sfb1451/motor-assessment/venv/lib/python3.7/site-packages/datalad_next/patches/push_to_export_remote.py", line 226, in _transfer_data
    "path": str(Path(res_kwargs["path"]) / result["file"])
  File "/usr/lib/python3.7/pathlib.py", line 901, in __truediv__
    return self._make_child((key,))
  File "/usr/lib/python3.7/pathlib.py", line 688, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.7/pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The relevant code fragment where error occurs (line 226) is:
https://github.com/datalad/datalad-next/blob/0804eb358d4ec8334b88a65d3659a5b606b61b26/datalad_next/patches/push_to_export_remote.py#L213-L237 

I tried the same from my laptop in a python 3.7 virtualenv and it worked, so it shouldn't be a python version.

Could it be git-annex version? Juseless has git-annex version: 8.20210310

**Comment by mslw** [comment]
Seems like it is about git-annex version. Updating to git-annex version: 10.20220504 made this problem go away (can also be considered confirmed working on 10.20220322, which is what my laptop has).

Side note: updating git-annex made another problem appear, but it is independent and easy to fix, so I'll post it in another issue and then close this one.
