### ISSUE TITLE
GOGS test instance broken

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#65]
It fails to delete a testrepo in a `finally` -- this likely means that the underlying test did not even manage to create it before.

```
======================================================================
1064ERROR: datalad_next.patches.tests.test_create_sibling_ghlike.test_gogs
1065----------------------------------------------------------------------
1066Traceback (most recent call last):
1067  File "/Users/appveyor/venv3.8.12/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
1068    self.test(*self.arg)
1069  File "/Users/appveyor/venv3.8.12/lib/python3.8/site-packages/nose/util.py", line 620, in newfunc
1070    return func(*arg, **kw)
1071  File "/Users/appveyor/venv3.8.12/lib/python3.8/site-packages/datalad/tests/utils.py", line 194, in _wrap_skip_if_no_network
1072    return func(*args, **kwargs)
1073  File "/Users/appveyor/venv3.8.12/lib/python3.8/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
1074    return t(*(arg + (filename,)), **kw)
1075  File "/Users/appveyor/venv3.8.12/lib/python3.8/site-packages/datalad/distributed/tests/test_create_sibling_gogs.py", line 35, in test_gogs
1076    check4real(
1077  File "/Users/appveyor/venv3.8.12/lib/python3.8/site-packages/datalad/distributed/tests/test_create_sibling_ghlike.py", line 183, in check4real
1078    requests.delete(
1079  File "/Users/appveyor/venv3.8.12/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
1080    raise HTTPError(http_error_msg, response=self)
1081requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://try.gogs.io/api/v1/repos/dataladtester/dltst_gogsctqqdqjs

```

And indeed, the underlying error is

```
[{'action': 'create_sibling_gogs',
  'message': 'initRepository: init repository: mkdir '
             '/home/git/gogs-repositories/dataladtester/dltst_gogs4lmgpppn.git: '
             'no space left on device',
  'refds': '/tmp/datalad_temp_test_gogs4lmgpppn',
  'status': 'error'}]
```

I verified that there are no stale repositories lying around in our tester account. It seems that the machine ran out of space.

I will disable the test for now, but disabling the credential on appveyor, causing the test to auto-skip.

**Comment by mih** [comment]
I manual test works again. I reenabled the credential for appveyor now.

**Comment by mih** [comment]
Tests run and pass.
